### PR TITLE
6 use case report user

### PR DESCRIPTION
**Pull request by ryancys1234**
### **Update as of 2022-11-21: This pull request containes significant progress on the report user, access report, AND restrict user use cases to the point that they are almost finished (save for the delete user functionality in the latter use case as well as linking the UI and writing the main file).**

**Note: please ignore the "Delete User.java" thing below. I had a duplicate User.java file and so I deleted it.**

**Note 2: the autograding check failed because of the Savable implementation in Review. We may need to ask the TA about this or on Piazza.**

**Note 3: there are several design decisions that I made. First, the attribute reports and the method addReport has been added in the abstract User class, instead of the RegularUser class. Second, the reports attribute is non-static (i.e., it depends on the instance variable). It being static can confer certain advantages, for instance being a centralized record of all reports in the application / system, which may look cleaner and less scattered. However, having reports be non-static means that whenever a user is deleted, those reports are deleted as well, thus saving space in the database.**

There are several changes that have been made.
- First, half of the functionality for the report user use case has been created. (Note that if there is any issue with the folder organization, please feel free to let me know.)
- Second, parts of the UI has been initiated, with the UserPageFrame representing the page that shows when you find a specific user, for instance.
- Third, the testing module has been started (albeit without functionality). 
- Fourth, some minor formatting changes were made to Profile.java.
- Fifth, in the User abstract class, the reports attribute has been added, as well as the addReport method.

### CODE REVIEW

**Review by Tristal25 — APPROVED** [review]
Overall good! A little suggestion: can have functions to add or edit reportText and supportingEvidence.

**Review by clarahqy — APPROVED** [review]
looks good to me. However the conflicts have to be solved first.

**Review by czz0120 — APPROVED** [review]
looks good

**Review by Tristal25 — APPROVED** [review]
Looks good for me

**Comment by ryancys1234** [comment]
There have been too many file conflicts since this pull request has not been merged in time. As such, I may open a separate pull request.

**Comment by ryancys1234** [comment]
There have been too many file conflicts since this pull request has not been merged in time. As such, I may open a separate pull request.

**Pull request closed without merging**
