### PR TITLE
DatabaseConnect add functions

### PR DESCRIPTION
**Pull request by Tristal25**
New functions for reviews and changed User related functions to accommodate changes

### CODE REVIEW

**Review by clarahqy — APPROVED** [review]
looks good to me

**Review by alexyin0429 — APPROVED** [review]
Great work!

**Review by czz0120 — DISMISSED** [review]
I think latter the Gateway class in the "green" layer need an abstraction, for dependency inversion reason

**Review by ryancys1234 — APPROVED** [review]
Looks good!

**Review by yifeiiZhang — DISMISSED** [review]

**Review by yifeiiZhang — APPROVED** [review]

**Review by xumiche7 — APPROVED** [review]
Look goods

**Review by czz0120 — APPROVED** [review]

**Pull request merged**
