### PR TITLE
44 create and implement class databaseconnect

### PR DESCRIPTION
**Pull request by Tristal25**
Completed part of DatabaseConnect, added loadProfile() function. This function loads Profile class from the database.

### CODE REVIEW

**Review by ryancys1234 — COMMENTED** [review]
loadProfile has a lot of if statements. They're probably the only way to do this (not entirely familiar with the function) but if there's a chance to make this less of a code smell I would encourage it.

**Review by clarahqy — APPROVED** [review]
looks good to me!

**Review by ryancys1234 — APPROVED** [review]

**Review by ryancys1234 — APPROVED** [review]
I wonder if it would be better that the class databaseconnect is referred to as databaseGateway, since it reflects its function better. As well, given the prevalence of repeated consecutive if statements several times in the code, I wonder if it would be possible to explore alternative methodologies of achieving the same purpose (for instance, there are if statements checking for specific cells in a table). Overall, good.

**Comment by clarahqy** [comment]
I was wondering if a single database-connect class is too large with too many methods. It could be split into several sub-classes and each class will focus on connecting one instance to the database, or it can implement several interfaces and each interface has methods connecting one instance to the database.

**Review by czz0120 — APPROVED** [review]

**Pull request merged**
