### PR TITLE
Completed test cases for recommend and all gateways, updated database

### PR DESCRIPTION
**Pull request by Tristal25**
Completed test cases for recommend and all gateways, updated database

### CODE REVIEW

**Review by ryancys1234 — DISMISSED** [review]
GOod

**Review by xumiche7 — DISMISSED** [review]

**Review by alexyin0429 — DISMISSED** [review]
good

**Review by czz0120 — APPROVED** [review]

**Review by ryancys1234 — APPROVED** [review]
Nice Readme and python work!

**Review by czz0120 — APPROVED** [review]
god

**Review by xumiche7 — APPROVED** [review]

**Pull request merged**
