### PR TITLE
Some modifications

### PR DESCRIPTION
**Pull request by clarahqy**
Delete the static int count in entity Review
Add a static int count in ReviewInteratcor, which represents the total number of reviews in database
Comment out hideReview method, will implement it if time permitted
Add a IReviewView interface and let screens implement it to enhance CA
Add a ReviewTestScreen for ReviewInteractorTest to work
Organize some packages

### CODE REVIEW

**Review by Tristal25 — DISMISSED** [review]
looks good

**Review by ryancys1234 — APPROVED** [review]
Solid work!

**Comment by clarahqy** [comment]
pr closed and will open a new branch after resolving the conflicts

**Comment by clarahqy** [comment]
This PR was closed because the conflicts were too complex

**Pull request closed without merging**
