### PR TITLE
add Javadoc for recommend use case

### PR DESCRIPTION
**Pull request by Tristal25**
add Javadoc for recommend use case and update some screen features

### CODE REVIEW

**Review by ryancys1234 — DISMISSED** [review]
Very thorough javadocs. Thanks!

**Review by xumiche7 — APPROVED** [review]
Good coding style and improvements look good.

**Review by czz0120 — DISMISSED** [review]

**Review by ryancys1234 — APPROVED** [review]
Solid!

**Review by yifeiiZhang — DISMISSED** [review]

**Review by ryancys1234 — APPROVED** [review]

**Comment by xumiche7** [comment]
Fixed the conflicts of search and log-in screen + update search test

**Pull request merged**
